version: '2'
services:

  sync-example.local:
      container_name: 'sync-example.local'
      build:
        context: ./
        dockerfile: dockerfile
      volumes:
        - ./../:/var/www/html
      ports:
        - '80:80'  # http
        - '443:443' # https
